apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  externalIPs: 
    - 10.146.0.2
    - 10.146.0.3
  ports: 
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector: 
      app: sample-app
